blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/X64Tyko/Pantheon/discussions
    about: Please ask questions or start discussions in GitHub Discussions.
