#include <gtest/gtest.h>
#include "conf/ConfStore.h"
#include <filesystem>
#include <fstream>
#include <cstdio>

namespace
{
	class ConfStoreTest : public ::testing::Test
	{
	protected:
		void SetUp() override
		{
			path = (std::filesystem::temp_directory_path()
				/ ("momus_kairos_conf_" + std::to_string(::testing::UnitTest::GetInstance()->random_seed())
					+ "_" + ::testing::UnitTest::GetInstance()->current_test_info()->name() + ".conf")).string();
			std::remove(path.c_str());
		}

		void TearDown() override { std::remove(path.c_str()); }

		std::string path;
	};
} // namespace

// Reported bug: the Settings page's "Sync Worker Threads" value reverted to
// whatever KAIROS_SYNC_THREADS the compose file sets (4) on every restart —
// setSyncThreadsOverride only ever updated SyncManager's in-memory atomic,
// never ConfStore's own persisted file. Simulates a restart by constructing
// a fresh ConfStore against the same path.
TEST_F(ConfStoreTest, SyncThreadsOverridePersistsAcrossRestart)
{
	{
		ConfStore conf(path);
		EXPECT_EQ(conf.getSyncThreadsOverride(), 0); // unset by default
		conf.setSyncThreadsOverride(16);
		EXPECT_EQ(conf.getSyncThreadsOverride(), 16);
	}
	{
		ConfStore reloaded(path); // fresh instance == restart
		EXPECT_EQ(reloaded.getSyncThreadsOverride(), 16);
	}
}

TEST_F(ConfStoreTest, SyncThreadsOverrideOfZeroClearsIt)
{
	ConfStore conf(path);
	conf.setSyncThreadsOverride(8);
	conf.setSyncThreadsOverride(0);
	EXPECT_EQ(conf.getSyncThreadsOverride(), 0);

	ConfStore reloaded(path);
	EXPECT_EQ(reloaded.getSyncThreadsOverride(), 0); // never written since it's the default
}

// Regression coverage for the fix to POST /api/channels/:id/played being
// globally unauthenticated (see CHANGELOG): the internal_token gate is only
// as good as the guarantee that a fresh install always has one.
TEST_F(ConfStoreTest, InternalTokenIsAutoGeneratedOnFirstRun)
{
	ConfStore conf(path);
	EXPECT_FALSE(conf.getInternalToken().empty());
}

TEST_F(ConfStoreTest, InternalTokenPersistsAcrossRestart)
{
	std::string first;
	{
		ConfStore conf(path);
		first = conf.getInternalToken();
		EXPECT_FALSE(first.empty());
	}
	{
		ConfStore reloaded(path); // fresh instance == restart
		EXPECT_EQ(reloaded.getInternalToken(), first);
	}
}

TEST_F(ConfStoreTest, InternalTokenIsEditableAndPersists)
{
	{
		ConfStore conf(path);
		conf.setInternalToken("my-custom-secret");
		EXPECT_EQ(conf.getInternalToken(), "my-custom-secret");
	}
	{
		ConfStore reloaded(path);
		EXPECT_EQ(reloaded.getInternalToken(), "my-custom-secret");
	}
}

// A conf file written before this field existed (no internal_token line at
// all) must still end up with one on next load — otherwise upgrading an
// existing install would leave /played permanently 401ing until an admin
// happened to notice and visit Settings.
TEST_F(ConfStoreTest, InternalTokenBackfillsOnUpgradeFromOlderConfFile)
{
	{
		std::ofstream f(path);
		f << "[_global]\ndownload_path = /downloads\n";
	}
	ConfStore conf(path);
	EXPECT_FALSE(conf.getInternalToken().empty());
	EXPECT_EQ(conf.getDownloadPath(), "/downloads"); // untouched
}

// setBufferSize had the same bug class: it updated the in-memory value (and
// the global g_buffer_size) but never called saveLocked(), so it silently
// reverted on restart too.
TEST_F(ConfStoreTest, BufferSizePersistsAcrossRestart)
{
	{
		ConfStore conf(path);
		conf.setBufferSize(2048); // KB
		EXPECT_EQ(conf.getBufferSize(), 2048);
	}
	{
		ConfStore reloaded(path);
		EXPECT_EQ(reloaded.getBufferSize(), 2048);
	}
}